/* Taobao copy-link price probe for Surge v1.13.0
 * Goal: capture item ID from share/copy-link related requests, then query Bijiago.
 * Safe: never exposes cookies/tokens/body values in panel.
 */
const req=$request||{}, resp=typeof $response!=='undefined'?$response:null;
const src=resp||req, body=src&&src.body, url=String(req.url||''), headers=(src&&src.headers)||req.headers||{};
const PANEL='taobao_analytics_probe_panel', LAST='taobao_copylink_last';
function text(v){if(typeof v==='string')return v;if(v&&typeof v==='object'&&typeof v.length==='number'){try{return new TextDecoder('utf-8').decode(v)}catch(_){try{return Array.from(v).map(x=>String.fromCharCode(x)).join('')}catch(__){}}}return''}
function dec(s){let x=String(s||'');for(let i=0;i<8;i++){try{const y=decodeURIComponent(x.replace(/\+/g,'%20'));if(y===x)break;x=y}catch(_){break}}return x}
function scan(s){s=dec(s);const out=[];const rs=[/(?:itemId|item_id|itemid|numId|num_id|auctionId|auction_id|goodsId|goods_id|skuId|sku_id)[\s\"'=:,%&\\/]+(?:%22|%27|[\"'])?(\d{8,20})/ig,/(?:[?&]|%26)(?:id|itemId|item_id|numId|auctionId)(?:=|%3D)(\d{8,20})/ig,/(?:item\.taobao\.com|detail\.tmall\.com|m\.tb\.cn|tb\.cn)[^\s\"']{0,1200}?(?:\?|&|%26)(?:id|itemId|item_id)(?:=|%3D)(\d{8,20})/ig,/\"(?:itemId|item_id|numId|auctionId|goodsId|skuId)\"\s*:\s*\"?(\d{8,20})/ig];for(const r of rs){let m;while((m=r.exec(s)))if(!out.includes(m[1]))out.push(m[1])}return out}
const raw=text(body), all=url+'\n'+raw;const ids=scan(all);let host='',path='/';try{const u=new URL(url);host=u.hostname;path=u.pathname||'/'}catch(_){host=url.replace(/^https?:\/\//,'').split('/')[0]}
const phase=resp?'RESP':'REQ', now=Date.now();
function save(msg,good){try{$persistentStore.write(JSON.stringify({message:msg,ids:!!good,time:now}),PANEL)}catch(_){}}
function finish(msg,good){save(msg,good);$done({})}
function queryPrice(id){const itemUrl=`https://detail.tmall.com/item.htm?id=${id}`;const t=Date.now();const cookieOpt={url:`https://browser.bijiago.com/extension?ac=bdextPermanent&format=json&version=${t}`,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36','Accept':'*/*'},timeout:5};$httpClient.get(cookieOpt,(e,r,d)=>{let cookie='';try{const h=(r&&r.headers)||{};const sc=h['Set-Cookie']||h['set-cookie']||'';cookie=Array.isArray(sc)?sc.join(';'):String(sc||'')}catch(_){}const opt={url:`https://browser.bijiago.com/extension/price_towards?url=${encodeURIComponent(itemUrl)}&format=jsonp&union=union_bijiago&from_device=bijiago&version=${Date.now()}`,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36','Referer':itemUrl,'Accept':'*/*','Cookie':cookie},timeout:8};$httpClient.get(opt,(err,rsp,data)=>{if(err||!data){finish(`时间: ${new Date().toLocaleString()}\n✅ 已抓到商品ID: ${id}\n比价狗接口暂未返回数据\n来源: ${phase} ${host}${path}`,true);return}let obj=null;try{obj=JSON.parse(String(data).trim().replace(/^[^(]*\(/,'').replace(/\)\s*;?$/,''))}catch(_){}let summary='历史价格数据已返回';try{const stores=obj&&obj.store?obj.store:(obj&&obj.data&&obj.data.store)||[];const s=Array.isArray(stores)&&stores.length?stores[stores.length>1?1:0]:null;if(s){const cur=s.last_price!=null?Number(s.last_price)/100:null;const lo=s.lowest!=null?Number(s.lowest):null;const hi=s.highest!=null?Number(s.highest):null;summary=`当前≈¥${cur!=null?cur.toFixed(2):'-'}｜最低≈¥${lo!=null?lo.toFixed(2):'-'}｜最高≈¥${hi!=null?hi.toFixed(2):'-'}`}}catch(_){}finish(`时间: ${new Date().toLocaleString()}\n✅ 淘宝商品ID: ${id}\n${summary}\n来源: ${phase} ${host}${path}`,true)})})}
if(ids.length){const id=ids[0];let last='';try{last=$persistentStore.read(LAST)||''}catch(_){};if(last!==id){try{$persistentStore.write(id,LAST)}catch(_){};queryPrice(id)}else finish(`时间: ${new Date().toLocaleString()}\n✅ 淘宝商品ID: ${id}\n已捕获，等待/保留上次比价结果\n来源: ${phase} ${host}${path}`,true)}else{finish(`时间: ${new Date().toLocaleString()}\n分享/复制链路已命中，暂未发现商品ID\n${phase} ${host}${path}\n请在淘宝商品页点“分享”→“复制链接”`,false)}
